/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gEtudiant;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbdeAMNR
 */
public class EtudiantInfos extends javax.swing.JFrame {

    /**
     * Creates new form EtudiantInfos
     */
    DefaultTableModel model = new DefaultTableModel() {
        /* set every cell in the table to no editable */
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };
    jdbcManager cnx = new jdbcManager();
    private Statement stm = null;
    private ResultSet rs = null;
    private final String userLevel = LoginFrame.userAuthority;

    public EtudiantInfos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTable();
        this.chargerTable();
        this.remplirCbxFiliere();
        /*verify admin rights */
        if (userLevel.equals("Etudiant")) {
            this.btAdd.setEnabled(false);
            this.btnDelete.setEnabled(false);
            this.btnUpdate.setEnabled(false);
            this.btnClear.setEnabled(false);
        }
    }

    public final void setTable() {
        model.addColumn("Etudiant id");
        model.addColumn("Nom et prenom");
        model.addColumn("Annee naissance");
        model.addColumn("Filiere");
        model.addColumn("Promotion");
        model.addColumn("Genre");
        model.addColumn("Adresse");
        model.addColumn("Telephone");
        model.addColumn("E-mail");
        /* design tableau*/
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(Color.decode("#157efb"));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setFont(new Font("tahoma", Font.BOLD, 16));

        //  jTable1.getTableHeader().setFont(Font.BOLD);
    }

    public final void chargerTable() {
        try {
            stm = cnx.obtenirconnexion().createStatement();
            rs = stm.executeQuery("SELECT e.Etudiant_id, e.nom_prenom, "
                    + "e.annee_naissance,f.filiere_nom,e.promo,e.genre,"
                    + "e.adresse,e.tele,e.email FROM etudiant_info e "
                    + "join filiere f on e.filiere= f.Filiere_id ");

            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("Etudiant_id"), rs.getString("nom_prenom"),
                    rs.getDate("annee_naissance"), rs.getString("filiere_nom"),
                    rs.getDate("promo"), rs.getString("genre"),
                    rs.getString("adresse"), rs.getString("tele"),
                    rs.getString("email")
                });
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        this.jTable1.setModel(model);
    }

    public final void remplirCbxFiliere() {
        try {
            Statement stmt = cnx.obtenirconnexion().createStatement();
            ResultSet reSet = stmt.executeQuery("SELECT * FROM filiere");
            this.cbxFiliere.removeAllItems();
            while (reSet.next()) {
                this.cbxFiliere.addItem(reSet.getString("filiere_nom"));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    public int getIdFiliere(String str) {
        int id;
        try {
            Statement stmt = cnx.obtenirconnexion().createStatement();
            ResultSet resultset = stmt.executeQuery("SELECT * FROM filiere WHERE filiere_nom = '" + str + "'");
            while (resultset.next()) {
                id = resultset.getInt("Filiere_id");
                return id;
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        cbxRecherche = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateChooserNaissance = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxGenre = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTele = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxFiliere = new javax.swing.JComboBox<>();
        yearChooserPromo = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        updatePhoto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSignOut = new javax.swing.JMenu();
        menuRefrech = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEtud = new javax.swing.JMenuItem();
        menuNotaton = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Etudiants");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(252, 74, 26));
        jTable1.setSelectionForeground(java.awt.Color.black);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Effectuer des modifications.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(234, 67, 53));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        cbxRecherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom_prenom", "tele", "email", "promo" }));

        jLabel2.setText("Recherche avec");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Commandes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N
        jPanel4.setName(""); // NOI18N

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudAdd.png"))); // NOI18N
        btAdd.setText("Ajouter");
        btAdd.setDisabledIcon(null);
        btAdd.setDisabledSelectedIcon(null);
        btAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAdd.setIconTextGap(15);
        btAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        btAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAddMouseExited(evt);
            }
        });
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudDelete.png"))); // NOI18N
        btnDelete.setText("Effacer");
        btnDelete.setIconTextGap(15);
        btnDelete.setPreferredSize(new java.awt.Dimension(160, 30));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudUpdatate.png"))); // NOI18N
        btnUpdate.setText("Modifier");
        btnUpdate.setIconTextGap(11);
        btnUpdate.setPreferredSize(new java.awt.Dimension(160, 30));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudClear.png"))); // NOI18N
        btnClear.setText("Clair");
        btnClear.setIconTextGap(25);
        btnClear.setPreferredSize(new java.awt.Dimension(160, 30));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Les informations d'Étudiant", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N

        jLabel3.setText("Nom et prénom :");

        jLabel5.setText("Date de naissance :");

        dateChooserNaissance.setDateFormatString("yyyy-MM-dd");
        dateChooserNaissance.setPreferredSize(new java.awt.Dimension(69, 22));

        jLabel9.setText("Adresse :");

        jLabel7.setText("Promotion :");

        cbxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel8.setText("Genre :");

        jLabel10.setText("Téléphone :");

        jLabel11.setText("Email :");

        jLabel6.setText("Filière :");

        yearChooserPromo.setDateFormatString("YYYY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateChooserNaissance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(yearChooserPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(185, 185, 185))
                    .addComponent(txtEmail)
                    .addComponent(txtTele)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(210, 210, 210))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(214, 214, 214))
                    .addComponent(cbxFiliere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTele)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFiliere))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(txtNomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdresse)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxGenre)
                    .addComponent(yearChooserPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 74, 26));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/Untitled-1.png"))); // NOI18N
        jLabel1.setText("Système de gestion des étudiants");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Photo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/noPhotoDifined.jpg"))); // NOI18N
        lblPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(234, 67, 53), 2, true));
        lblPhoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        updatePhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updatePhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudUpdatate.png"))); // NOI18N
        updatePhoto.setText("Modifier / Ajouter");
        updatePhoto.setBorder(null);
        updatePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updatePhoto.setHideActionText(true);
        updatePhoto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        updatePhoto.setIconTextGap(11);
        updatePhoto.setOpaque(false);
        updatePhoto.setPreferredSize(new java.awt.Dimension(160, 30));
        updatePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuSignOut.setText("File");

        menuRefrech.setText("Actualiser");
        menuRefrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRefrechActionPerformed(evt);
            }
        });
        menuSignOut.add(menuRefrech);

        jMenuItem5.setText("Se déconnecter");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuSignOut.add(jMenuItem5);

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSignOut.add(jMenuItem1);

        jMenuBar1.add(menuSignOut);

        jMenu2.setText("Edit");

        menuEtud.setText("Etudiants");
        menuEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEtudActionPerformed(evt);
            }
        });
        jMenu2.add(menuEtud);

        menuNotaton.setText("Notations");
        menuNotaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotatonActionPerformed(evt);
            }
        });
        jMenu2.add(menuNotaton);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        menuAbout.setText("about");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int OptionChoisie = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer les informations de cet étudiant?", "Attendez une seconde", JOptionPane.YES_NO_OPTION);
        if (OptionChoisie == 0) {
            int row = -1;
            row = jTable1.getSelectedRow();
            /*check if row selected in jtable*/
            if (row != -1) {
                int value = (int) jTable1.getValueAt(row, 0);
                String del_Query = "DELETE FROM etudiant_info WHERE Etudiant_id= " + value;
                System.out.println(del_Query);
                int effects = cnx.update(del_Query);
                System.out.println(effects + " deleted row(s)");
                chargerTable();
            } else {
                JOptionPane.showMessageDialog(this, "error", "Please select a student ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = -1;
        row = jTable1.getSelectedRow();
        if (row != -1) {
            int value = (int) jTable1.getValueAt(row, 0);

            String nom_Prenom = this.txtNomPrenom.getText();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String annee_naissance = (String) sdf.format(this.dateChooserNaissance.getDate());

            String fili = (String) this.cbxFiliere.getSelectedItem();
            int filiere = getIdFiliere(fili);

            SimpleDateFormat sdfyear = new SimpleDateFormat("yyyy");
            String promo = (String) sdfyear.format(this.yearChooserPromo.getDate());

            String genre = (String) this.cbxGenre.getSelectedItem();
            String adresse = this.txtAdresse.getText();
            String tele = this.txtTele.getText();
            String email = this.txtEmail.getText();

            String rqtUpdate = "UPDATE etudiant_info SET nom_prenom = '" + nom_Prenom + "', annee_naissance = '" + annee_naissance + "', filiere = " + filiere + " , promo = '" + promo + "', genre = '" + genre + "', adresse = '" + adresse + "', tele = '" + tele + "', email = '" + email + "' WHERE Etudiant_id = " + value;
            System.out.println(rqtUpdate);
            int effects = cnx.update(rqtUpdate);
            System.out.println(effects + " updated row(s)");
            chargerTable();
        } else {
            JOptionPane.showMessageDialog(this, "error", "Please select a student ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void menuEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEtudActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_menuEtudActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            stm = cnx.obtenirconnexion().createStatement();
            rs = stm.executeQuery("SELECT * FROM etudiant_info WHERE nom_prenom ='"
                    + "" + this.txtNomPrenom.getText() + "'");
            if (!rs.first()) {
                String annee_naissance = "2000-01-01";
                String promo = "2000";
                if (!LoginFrame.isNullOrWhiteSpace(this.txtNomPrenom.getText())) {
                    String nomPrenom = this.txtNomPrenom.getText();
                    if (this.dateChooserNaissance.getDate() != null) {
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        annee_naissance = (String) sdf.format(this.dateChooserNaissance.getDate());
                    }
                    String fili = (String) this.cbxFiliere.getSelectedItem();
                    int filiere = getIdFiliere(fili);
                    if (this.yearChooserPromo.getDate() != null) {
                        SimpleDateFormat sdfyear = new SimpleDateFormat("yyyy");
                        promo = (String) sdfyear.format(this.yearChooserPromo.getDate());
                    }
                    String genre = (String) this.cbxGenre.getSelectedItem();
                    String adresse = this.txtAdresse.getText();
                    String tele = this.txtTele.getText();
                    String email = this.txtEmail.getText();
                    String rqtInsert = "INSERT INTO etudiant_info (nom_prenom , annee_naissance ,filiere,promo,  genre , adresse ,  tele , email ) "
                            + "VALUES ('" + nomPrenom + "','" + annee_naissance + "'," + filiere + ",'" + promo + "','" + genre + "','" + adresse + "','" + tele + "','" + email + "')";
                    System.out.println(rqtInsert);
                    int c = cnx.update(rqtInsert);

                    chargerTable();
                    JOptionPane.showMessageDialog(null, c + " Enregistrement bien ajouter", "Etat de L'operation", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Champ vide ou il y a des espaces", "Invalide", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "already exist", "Invalide", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            System.err.println(ex);
        } finally {
            try {
                rs.close();
                stm.close();
            } catch (SQLException ex) {
                Logger.getLogger(EtudiantInfos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btAddActionPerformed
    public void runSearch() {
        try {
            String req = "SELECT e.Etudiant_id, e.nom_prenom, "
                    + "e.annee_naissance,f.filiere_nom,e.promo,e.genre,"
                    + "e.adresse,e.tele,e.email FROM etudiant_info e "
                    + "join filiere f on e.filiere= f.Filiere_id"
                    + " where e." + this.cbxRecherche.getSelectedItem()
                    + " like '%" + this.txtSearch.getText() + "%'";
            System.out.println(req);

            Statement stm2 = cnx.obtenirconnexion().createStatement();
            ResultSet Rs = stm2.executeQuery(req);

            model.setRowCount(0);
            while (Rs.next()) {
                model.addRow(new Object[]{
                    Rs.getInt("e.Etudiant_id"), Rs.getString("e.nom_prenom"),
                    Rs.getDate("e.annee_naissance"), Rs.getString("f.filiere_nom"),
                    Rs.getDate("e.promo"), Rs.getString("e.genre"),
                    Rs.getString("e.adresse"), Rs.getString("e.tele"),
                    Rs.getString("e.email")
                });
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        this.jTable1.setModel(model);
    }
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        runSearch();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        this.txtAdresse.setText("");
        this.txtEmail.setText("");
        this.txtNomPrenom.setText("");
        this.txtSearch.setText("");
        this.txtTele.setText("");
        this.chargerTable();

    }//GEN-LAST:event_btnClearActionPerformed
    private void setImageToDefault() {
        try {
            File fichier = new File("src/GestionEtudiant2017/myFiles/noPhotoDifined.jpg");
            Image image = ImageIO.read(fichier);
            lblPhoto.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(EtudiantInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getPhoto() {
        int row = jTable1.getSelectedRow();
        int value = (int) jTable1.getValueAt(row, 0);
        try {
            stm = cnx.obtenirconnexion().createStatement();
            rs = stm.executeQuery("SELECT e.photo FROM etudiant_info e WHERE e.Etudiant_id=" + value);
            if (rs.first()) {
                String link = rs.getString("photo");
                if (rs.wasNull() && rs.getObject("photo") == null) {
                    setImageToDefault();
                } else {
                    File fichier = new File(link);
                    Image image = ImageIO.read(fichier);
                    lblPhoto.setIcon(new ImageIcon(image));
                }
            }
        } catch (IOException | SQLException ex) {
            System.err.println(ex);
        }
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        this.txtNomPrenom.setText((String) jTable1.getValueAt(row, 1));
        this.dateChooserNaissance.setDate((Date) jTable1.getValueAt(row, 2));
        this.txtAdresse.setText((String) jTable1.getValueAt(row, 6));
        this.cbxGenre.setSelectedItem((String) jTable1.getValueAt(row, 5));
        this.yearChooserPromo.setDate((Date) jTable1.getValueAt(row, 4));
        this.txtTele.setText((String) jTable1.getValueAt(row, 7));
        this.txtEmail.setText((String) jTable1.getValueAt(row, 8));

        getPhoto();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setVisible(false);
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuNotatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotatonActionPerformed
        Notation not = new Notation();
        /*show() methode is the same as setVisible(boolean)*/
        not.show();
        this.setVisible(false);
    }//GEN-LAST:event_menuNotatonActionPerformed

    private void menuRefrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRefrechActionPerformed
        btnClearActionPerformed(evt);
        chargerTable();
        setImageToDefault();
    }//GEN-LAST:event_menuRefrechActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        /*==Instantiation de jpanel==*/
        AboutFrame me = new AboutFrame();

        JDialog frame = new JDialog(this, "A propos", true);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(me);
        frame.pack();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void updatePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhotoActionPerformed

        int row = jTable1.getSelectedRow();
        int value = (int) jTable1.getValueAt(row, 0);
        String name = (String) jTable1.getValueAt(row, 1);
        File f = new File("lib\\\\photoEtudiants\\\\" + name + ".jpg");
        if (f.exists()) {
            try {
                String rqt = "UPDATE etudiant_info set photo= 'lib\\\\photoEtudiants\\\\" + name + ".jpg' WHERE Etudiant_id= " + value;

                PreparedStatement stmt = cnx.obtenirconnexion().prepareStatement(rqt);
                System.out.println(rqt);
                stmt.executeUpdate(rqt);

                getPhoto();
            } catch (SQLException ex) {
                System.err.println(ex);
            }
            /**
             * JFileChooser chooser = new JFileChooser(); File file = null;
             * String filePath = null; int row = jTable1.getSelectedRow(); int
             * value = (int) jTable1.getValueAt(row, 0); int returnValue =
             * chooser.showOpenDialog(null); PreparedStatement stmt = null;
             *
             * if (returnValue == JFileChooser.APPROVE_OPTION) { file =
             * chooser.getSelectedFile(); filePath =
             * file.getParentFile().getName().replace("\\", "\\\\");
             * System.out.println("voila\n" + filePath); try { String rqt =
             * "UPDATE etudiant_info set photo= " + filePath + " WHERE
             * Etudiant_id= " + value;
             *
             * stmt = cnx.obtenirconnexion().prepareStatement(rqt);
             * //stmt.setString(1, filePath); stmt.executeUpdate(rqt);
             *
             * getPhoto(); stmt.close(); } catch (SQLException ex) {
             * System.err.println(ex); } }
             */
        } else {
            JOptionPane.showMessageDialog(this, "L'image n'existe pas dans le dossier lib\\photoEtudiants avec le nom " + name + ".jpg", "existe pas", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updatePhotoActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        runSearch();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddMouseEntered
       btAdd.setForeground(Color.decode("#FC4A1A"));
    }//GEN-LAST:event_btAddMouseEntered

    private void btAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddMouseExited
       btAdd.setForeground(Color.BLACK);
    }//GEN-LAST:event_btAddMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
btnDelete.setForeground(Color.decode("#FC4A1A"));
     
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
          btnDelete.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
   btnUpdate.setForeground(Color.decode("#FC4A1A"));

    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
      btnUpdate.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
       btnClear.setForeground(Color.decode("#FC4A1A"));
      
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
     btnClear.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnClearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtudiantInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtudiantInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtudiantInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new EtudiantInfos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxFiliere;
    private javax.swing.JComboBox<String> cbxGenre;
    private javax.swing.JComboBox<String> cbxRecherche;
    private com.toedter.calendar.JDateChooser dateChooserNaissance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuEtud;
    private javax.swing.JMenuItem menuNotaton;
    private javax.swing.JMenuItem menuRefrech;
    private javax.swing.JMenu menuSignOut;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomPrenom;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTele;
    private javax.swing.JButton updatePhoto;
    private com.toedter.calendar.JDateChooser yearChooserPromo;
    // End of variables declaration//GEN-END:variables
}
