/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gEtudiant;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbdeAMNR
 */
public class Notation extends javax.swing.JFrame {
    
    int Etudiant_id;
    double note_E2;
    double note_E3;
    double note_E4;
    double note_E5;
    double note_E11;
    double note_E12;
    double note_E13;
    double note_E61;
    double note_E62;
    double moyenne_Generale;
    /**
     * Creates new form Notation
     */
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };
    jdbcManager cnx = new jdbcManager();
    private Statement stm = null;
    private ResultSet rs = null;
    private final String userLevel = LoginFrame.userAuthority;
    private boolean test = false;
    
    public Notation() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panelGerer.setVisible(false);
        setTable();
        chargerTable();
        remplirCbxEtudiant();
        
        if (userLevel.equals("Etudiant")) {
            this.btnGerer.setEnabled(false);
        }
        
    }
    
    public final void setTable() {
        
        model.addColumn("Notes id");
        model.addColumn("Etudiant id");
        model.addColumn("Nom et prenom");
        model.addColumn("note_E2");
        model.addColumn("note_E3");
        model.addColumn("note_E4");
        model.addColumn("note_E5");
        model.addColumn("note_E11");
        model.addColumn("note_E12");
        model.addColumn("note_E13");
        model.addColumn("note_E61");
        model.addColumn("note_E62");
        model.addColumn("Moyenne generale");
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(Color.decode("#157efb"));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setFont(new Font("tahoma", Font.BOLD, 16));
    }
    
    public final void chargerTable() {
        try {
            stm = cnx.obtenirconnexion().createStatement();
            String rqt = "SELECT n.Notes_id,n.Etudiant_id,e.nom_prenom,n.note_E2,n.note_E3,"
                    + "n.note_E4,n.note_E5,n.note_E11,n.note_E12,n.note_E13,n.note_E61,n.note_E62,"
                    + "n.moyenne_Generale FROM notation n join etudiant_info e on n.Etudiant_id=e.Etudiant_id";
            rs = stm.executeQuery(rqt);
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("n.Notes_id"), rs.getInt("n.Etudiant_id"),
                    rs.getString("e.nom_prenom"), rs.getDouble("n.note_E2"),
                    rs.getDouble("n.note_E3"),
                    rs.getDouble("n.note_E4"), rs.getDouble("n.note_E5"),
                    rs.getDouble("n.note_E11"), rs.getDouble("n.note_E12"),
                    rs.getDouble("n.note_E13"), rs.getDouble("n.note_E61"),
                    rs.getDouble("n.note_E62"), rs.getDouble("n.moyenne_Generale")});
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        this.jTable1.setModel(model);
    }
    
    public final void remplirCbxEtudiant() {
        this.cbxEtudiant.removeAllItems();
        try {
            Statement stmt = cnx.obtenirconnexion().createStatement();
            ResultSet reSet = stmt.executeQuery("SELECT * FROM etudiant_info");
            
            while (reSet.next()) {
                this.cbxEtudiant.addItem(reSet.getString("nom_prenom"));
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGerer = new javax.swing.JPanel();
        cbxEtudiant = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtE11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtE5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtE4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtE3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtE2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtE13 = new javax.swing.JTextField();
        txtE61 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtE12 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMoyG = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtE62 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGerer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        notationRefrech = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSignOut = new javax.swing.JMenu();
        menuRefrech = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEtud = new javax.swing.JMenuItem();
        menuNotaton = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notation");

        panelGerer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gestion des notes :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N

        cbxEtudiant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEtudiant.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel2.setText("Gérer les notes de l’étudiant :");

        txtE11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE11.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("note_E4");

        txtE5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE5.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("note_E2");

        txtE4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE4.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("note_E11");

        txtE3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE3.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("note_E12");

        txtE2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE2.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("note_E61:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("note_E13");

        txtE13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE13.setPreferredSize(new java.awt.Dimension(50, 25));

        txtE61.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE61.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("note_E5");

        txtE12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE12.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("note_E3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("moyenne_Generale:");

        txtMoyG.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMoyG.setPreferredSize(new java.awt.Dimension(50, 25));

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudAdd.png"))); // NOI18N
        btAdd.setText("Ajouter");
        btAdd.setPreferredSize(new java.awt.Dimension(100, 35));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudDelete.png"))); // NOI18N
        btnDelete.setText("Effacer");
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudClear.png"))); // NOI18N
        btnClear.setText("Clair");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionEtudiant2017/myFiles/EtudUpdatate.png"))); // NOI18N
        btnUpdate.setText("Modifier");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("note_E62:");

        txtE62.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtE62.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout panelGererLayout = new javax.swing.GroupLayout(panelGerer);
        panelGerer.setLayout(panelGererLayout);
        panelGererLayout.setHorizontalGroup(
            panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGererLayout.createSequentialGroup()
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGererLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMoyG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)))
                    .addGroup(panelGererLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGererLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbxEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGererLayout.createSequentialGroup()
                            .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtE61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtE62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        panelGererLayout.setVerticalGroup(
            panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGererLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtE11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtE12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtE13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtE61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtE62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMoyG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Les résultats finaux des étudiants", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(66, 133, 244))); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(252, 74, 26));
        jTable1.setSelectionForeground(java.awt.Color.black);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGerer.setBackground(new java.awt.Color(252, 74, 26));
        btnGerer.setText("Gerer");
        btnGerer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerer.setPreferredSize(new java.awt.Dimension(90, 30));
        btnGerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGererActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Recherche par Nom: ");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 30));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        notationRefrech.setBackground(new java.awt.Color(252, 74, 26));
        notationRefrech.setText("Actualiser");
        notationRefrech.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notationRefrech.setPreferredSize(new java.awt.Dimension(90, 30));
        notationRefrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notationRefrechActionPerformed(evt);
            }
        });

        menuSignOut.setText("File");

        menuRefrech.setText("Actualiser");
        menuRefrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRefrechActionPerformed(evt);
            }
        });
        menuSignOut.add(menuRefrech);

        jMenuItem5.setText("Se déconnecter");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuSignOut.add(jMenuItem5);

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSignOut.add(jMenuItem1);

        jMenuBar1.add(menuSignOut);

        jMenu2.setText("Edit");

        menuEtud.setText("Etudiants");
        menuEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEtudActionPerformed(evt);
            }
        });
        jMenu2.add(menuEtud);

        menuNotaton.setText("Notations");
        menuNotaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotatonActionPerformed(evt);
            }
        });
        jMenu2.add(menuNotaton);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        menuAbout.setText("about");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelGerer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notationRefrech, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notationRefrech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGerer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setVisible(false);
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuRefrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRefrechActionPerformed
        btnClearActionPerformed(evt);
        this.chargerTable();
    }//GEN-LAST:event_menuRefrechActionPerformed

    private void menuEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEtudActionPerformed
        EtudiantInfos e = new EtudiantInfos();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEtudActionPerformed

    private void menuNotatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotatonActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_menuNotatonActionPerformed

    private void btnGererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGererActionPerformed
        if (test != true) {
            this.test = true;
            this.panelGerer.setVisible(true);
        } else {
            this.test = false;
            this.panelGerer.setVisible(false);
        }
    }//GEN-LAST:event_btnGererActionPerformed
    public int getIndex(String nomPrenom) {
        int index = 0;
        try {
            stm = cnx.obtenirconnexion().createStatement();
            String rqt = "SELECT * FROM etudiant_info WHERE nom_prenom LIKE '%" + nomPrenom + "%' ";
            rs = stm.executeQuery(rqt);
            while (rs.next()) {
                index = rs.getInt("Etudiant_id");
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        return index;
    }
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            if (!LoginFrame.isNullOrWhiteSpace(this.txtE2.getText())) {
                Etudiant_id = this.getIndex((String) this.cbxEtudiant.getSelectedItem());
                note_E2 = Double.parseDouble(this.txtE2.getText());
                note_E3 = Double.parseDouble(this.txtE3.getText());
                note_E4 = Double.parseDouble(this.txtE4.getText());
                note_E5 = Double.parseDouble(this.txtE5.getText());
                note_E11 = Double.parseDouble(this.txtE11.getText());
                note_E12 = Double.parseDouble(this.txtE12.getText());
                note_E13 = Double.parseDouble(this.txtE13.getText());
                note_E61 = Double.parseDouble(this.txtE61.getText());
                note_E62 = Double.parseDouble(this.txtE61.getText());
                moyenne_Generale = Double.parseDouble(this.txtMoyG.getText());
                
                String rqt = "INSERT INTO notation (Etudiant_id,note_E2,note_E3,note_E4,note_E5,note_E11,note_E12,note_E13,note_E61,note_E62,moyenne_Generale )  "
                        + "VALUES (" + Etudiant_id + "," + note_E2 + "," + note_E3 + "," + note_E4 + "," + note_E5 + "," + note_E11 + "," + note_E12 + "," + note_E13 + "," + note_E61 + "," + note_E62 + "," + moyenne_Generale + ")";
                System.out.println(rqt);
                int c = cnx.update(rqt);
                
                chargerTable();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "insert at lest the firts mark", "Invalid", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (HeadlessException | NumberFormatException ex) {
            System.err.println(ex);
        }

    }//GEN-LAST:event_btAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int OptionChoisie = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer les informations de cet étudiant?", "Attendez une seconde", JOptionPane.YES_NO_OPTION);
        if (OptionChoisie == 0) {
            int row = -1;
            row = jTable1.getSelectedRow();
            if (row != -1) {
                int value = (int) jTable1.getValueAt(row, 1);
                
                String req = "DELETE FROM notation WHERE Etudiant_id= " + value;
                System.out.println(req);
                int effects = cnx.update(req);
                System.out.println(effects + " row(s) deleted");
                this.chargerTable();
            } else {
                JOptionPane.showMessageDialog(this, "error", "Please select a student ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = -1;
        row = jTable1.getSelectedRow();
        if (row != -1) {
            try {
                
                Etudiant_id = this.getIndex((String) this.cbxEtudiant.getSelectedItem());
                note_E2 = Double.parseDouble(this.txtE2.getText());
                note_E3 = Double.parseDouble(this.txtE3.getText());
                note_E4 = Double.parseDouble(this.txtE4.getText());
                note_E5 = Double.parseDouble(this.txtE5.getText());
                note_E11 = Double.parseDouble(this.txtE11.getText());
                note_E12 = Double.parseDouble(this.txtE12.getText());
                note_E13 = Double.parseDouble(this.txtE13.getText());
                note_E61 = Double.parseDouble(this.txtE61.getText());
                note_E62 = Double.parseDouble(this.txtE62.getText());
                moyenne_Generale = Double.parseDouble(this.txtMoyG.getText());
                
                String rqt = "UPDATE notation SET note_E2=" + note_E2 + ",note_E3=" + note_E3 + ",note_E4=" + note_E4 + ",note_E5=" + note_E5 + ",note_E11="
                        + note_E11 + ",note_E12=" + note_E12 + ",note_E13=" + note_E13 + ",note_E61=" + note_E61 + ", note_E62=" + note_E62
                        + ", moyenne_Generale=" + moyenne_Generale + " where Etudiant_id=" + Etudiant_id;
                System.out.println(rqt);
                int c = cnx.update(rqt);
                
                chargerTable();
                javax.swing.JOptionPane.showMessageDialog(null, c + " Enregistrement bien ajouter", "Etat de L'operation", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            } catch (HeadlessException | NumberFormatException ex) {
                System.err.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "error", "Please select a student ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.txtSearch.setText("");
        this.txtE2.setText("");
        this.txtE3.setText("");
        this.txtE4.setText("");
        this.txtE5.setText("");
        this.txtE11.setText("");
        this.txtE12.setText("");
        this.txtE13.setText("");
        this.txtE61.setText("");
        this.txtE62.setText("");
        this.txtMoyG.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void notationRefrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notationRefrechActionPerformed
        menuRefrechActionPerformed(evt);
    }//GEN-LAST:event_notationRefrechActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        AboutFrame me = new AboutFrame();
        me.removeAll();
        JDialog frame = new JDialog(this, "A propos de le développeur de cette application", true);

        //  frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
        //add content to jpanel
        frame.getContentPane().removeAll();
        frame.getContentPane().add(me);
        frame.pack();
        //center jpanel  
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
//        me = null;
//        frame = null;

    }//GEN-LAST:event_menuAboutActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        
        this.cbxEtudiant.setSelectedItem(jTable1.getValueAt(row, 2));
        
        this.txtE2.setText(String.valueOf(jTable1.getValueAt(row, 3)));
        this.txtE3.setText(String.valueOf(jTable1.getValueAt(row, 4)));
        this.txtE4.setText(String.valueOf(jTable1.getValueAt(row, 5)));
        this.txtE5.setText(String.valueOf(jTable1.getValueAt(row, 6)));
        this.txtE11.setText(String.valueOf(jTable1.getValueAt(row, 7)));
        this.txtE12.setText(String.valueOf(jTable1.getValueAt(row, 8)));
        this.txtE13.setText(String.valueOf(jTable1.getValueAt(row, 9)));
        this.txtE61.setText(String.valueOf(jTable1.getValueAt(row, 10)));
        this.txtE62.setText(String.valueOf(jTable1.getValueAt(row, 11)));
        this.txtMoyG.setText(String.valueOf(jTable1.getValueAt(row, 12)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
try {
            stm = cnx.obtenirconnexion().createStatement();
            String rqt = "SELECT n.Notes_id,n.Etudiant_id,e.nom_prenom,n.note_E2,n.note_E3,"
                    + "n.note_E4,n.note_E5,n.note_E11,n.note_E12,n.note_E13,n.note_E61,n.note_E62,"
                    + "n.moyenne_Generale FROM notation n join etudiant_info e on n.Etudiant_id=e.Etudiant_id where n.Etudiant_id= " + this.getIndex(this.txtSearch.getText());
            rs = stm.executeQuery(rqt);
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("n.Notes_id"), rs.getInt("n.Etudiant_id"),
                    rs.getString("e.nom_prenom"), rs.getDouble("n.note_E2"),
                    rs.getDouble("n.note_E3"),
                    rs.getDouble("n.note_E4"), rs.getDouble("n.note_E5"),
                    rs.getDouble("n.note_E11"), rs.getDouble("n.note_E12"),
                    rs.getDouble("n.note_E13"), rs.getDouble("n.note_E61"),
                    rs.getDouble("n.note_E62"), rs.getDouble("n.moyenne_Generale")
                
                });
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
        this.jTable1.setModel(model);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new Notation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGerer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxEtudiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuEtud;
    private javax.swing.JMenuItem menuNotaton;
    private javax.swing.JMenuItem menuRefrech;
    private javax.swing.JMenu menuSignOut;
    private javax.swing.JButton notationRefrech;
    private javax.swing.JPanel panelGerer;
    private javax.swing.JTextField txtE11;
    private javax.swing.JTextField txtE12;
    private javax.swing.JTextField txtE13;
    private javax.swing.JTextField txtE2;
    private javax.swing.JTextField txtE3;
    private javax.swing.JTextField txtE4;
    private javax.swing.JTextField txtE5;
    private javax.swing.JTextField txtE61;
    private javax.swing.JTextField txtE62;
    private javax.swing.JTextField txtMoyG;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
